services:
  # Dashboard service
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
    restart: unless-stopped
    container_name: bigdata5-dashboard
  # API service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    restart: unless-stopped
    container_name: bigdata5-api
